version: '3.1'
services:
  stats-server:
    build: stats/service
    image: stats
    container_name: 'stats-server'
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: 'stats-db'
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"

  ewm-service:
    build: ewm
    image: ewm
    container_name: 'ewm-server'
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: 'ewm-db'
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
      PGDATA: /data/postgres
    ports:
      - "5433:5432"