server:
  port: 8080

spring:
  application:
    name: ewm
  datasource:
    username: ewm
    password: ewm
    url: jdbc:postgresql://localhost:5432/ewm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
      show-sql: true
    hibernate:
      ddl-auto: update
